### ISSUE TITLE
Easy to decrypt

### ISSUE THREAD

**Issue by arshidkv12** [hoowa/PHP-FRICC2#1]
Thanks for your efforts.
I can easily decrypt encoded php file with it (During execution time)

Skype: arshidkv12

**Comment by hoowa** [comment]
awesome

**Comment by hoowa** [comment]
hi buddy

did u delete my issue response in your phpbolt, how do you afraid my project, because your project didn't support PHP8 or what?

**Comment by arshidkv12** [comment]
Sorry.. No ads allowed. Do you want proof ( decryption )?
