### ISSUE TITLE
phar package encryption error cannot be executed

### ISSUE THREAD

**Issue by etjson** [hoowa/PHP-FRICC2#2]
![image](https://user-images.githubusercontent.com/41315967/132151901-c8e328ac-2c9d-47eb-8b0d-1b7bbbce4d6d.png)

I hope the author can support the encryption of phar packages. I'm using hyperf framework and I haven't been able to find an encryption protection scheme.

I implore the author to consider helping.

Thank you very much.

**Comment by hoowa** [comment]
hi etjson

please reproduce how to install hyperf and how to show this problem.

we can try to find how to fix it.

Thank you

**Comment by etjson** [comment]
> hi etjson
> 
> please reproduce how to install hyperf and how to show this problem.
> 
> we can try to find how to fix it.
> 
> Thank you

[https://hyperf.wiki/2.1/#/en/quick-start/install](https://hyperf.wiki/2.1/#/en/quick-start/install)

This is the way to install the framework, no need to make any changes after installation, directly packaged

Installing Packaged Components : 

composer require hyperf/phar

Then execute the packaging instruction : 

php bin/hyperf.php phar:build

This is the way I currently use the project packaging test on my side, but also can use the php native functions for packaging the simplest of a package, the execution of the words also failed.

This is the official phar packaging instructions provided by php : 
[https://www.php.net/manual/zh/book.phar.php](https://www.php.net/manual/zh/book.phar.php)

**Comment by etjson** [comment]
@hoowa 

github can search all look, google also searched, did not find any phar encryption scheme.

If the phar package does not support direct encryption, is it possible to batch encrypt the files before packaging them?

I tried it, but I found that most of the php encryption extensions encrypt the files in plain cipher text, for example

a1234567 xxxxxxxxxxxxxxxxxxx ciphertext xxxxxxxxxxxxxxx

And this a1234567 is the header information for file identification

What if this is the case?

\<?php enc_load('xxxxxxxxxxxxxxxx ciphertext xxxxxxxxxxxxxxx'); ?\>

In this case is it possible to encrypt the file and then package it.

But I didn't find a batch encryption tool like this.

I was doing everything I could to protect the php projects that the company wanted to distribute.

I'm begging the author to help me, I don't know c, if there is a way to encrypt phar files directly that would be great!

**Comment by etjson** [comment]
@hoowa 

Is there a way to package the php source code or php files together inside a c extension and name a function name and then call that function directly in the php file equivalent to executing that php program?

Maybe this idea is wrong or doesn't exist.

T.T sad ~~~

**Comment by hoowa** [comment]
because php-c had hook some special functions, c extension can decrypt php source file.
in fricc2 we replace zend_compile_file to customized c extension function.

i think you can continue to search on github, some other encoder program may supported this solution.
<?php enc_load('xxxxxxxxxxxxxxxx ciphertext xxxxxxxxxxxxxxx'); ?>

**Comment by hoowa** [comment]
@etjson 

goot news for u,  we update this project to support:
1. automatic ignore .phar / phar://
2. add sandbox mode, to enable only encrypted php source can run(also ignore phar)

would u like to test it?

thank you

**Comment by etjson** [comment]
@hoowa 

Ok, glad to be of help, thanks a lot, I'll try it right away.

**Comment by etjson** [comment]
@hoowa 

![QQ浏览器截图20210911223358](https://user-images.githubusercontent.com/41315967/132951372-9147eb90-4476-4e4f-962d-073e80a4b12c.png)

Still not working.

**Comment by etjson** [comment]
@hoowa 

I have successfully solved this problem with other encryption methods, but I am still very much looking forward to using your encryption plugin in a production environment.

If you need to cooperate with the test feel free to find me.

Thank you for your support of my feedback, much appreciated!
