### ISSUE TITLE
hoowa您好，有几点问题！

### ISSUE THREAD

**Issue by ScriptElite** [hoowa/PHP-FRICC2#8]
hoowa您好，有几点问题，希望抽空解答，谢谢！
1、多个PHP版本扩展的编译，要分别编译吗？比如我当前在php7.4下 ，编译成功了load.so文件，如果我想再编译一份其他版本的，还需要重新从头执行一次？或者有其他方法？
2、能否支持文件夹加密，即将目标文件夹内的所有文件批量加密？
3、怎样修改hellokitty？如果可以而且不影响版权的情况下！
4、能否在加密的时候生成指定的注释内容？
感谢

**Comment by hoowa** [comment]
reishi ***@***.***> 于2022年4月6日周三 00:10写道：

> hoowa您好，有几点问题，希望抽空解答，谢谢！
> 1、多个PHP版本扩展的编译，要分别编译吗？比如我当前在php7.4下
> ，编译成功了load.so文件，如果我想再编译一份其他版本的，还需要重新从头执行一次？或者有其他方法？
>
是的，但是如果key相同也可以通用。

> 2、能否支持文件夹加密，即将目标文件夹内的所有文件批量加密？
>
不能处理文件夹，PHP并不对文件夹进行handler处理。

> 3、怎样修改hellokitty？如果可以而且不影响版权的情况下！
>
已加密的文件不能直接修改，任何修改都将视为篡改。

> 4、能否在加密的时候生成指定的注释内容？
>
二进制文件的注释没有查看的意义把？

**Comment by ScriptElite** [comment]
**是的，但是如果key相同也可以通用。**
key相同，在php7.4下编译出的so也可以在PHP7.3下使用吗？

**Comment by hoowa** [comment]
这个问题，可能需要探索下了

**Comment by ScriptElite** [comment]
我找到了一个方法，make clean 但还没有去尝试，而且之前在编译so的时候输入了错误的命令，虽然不致命，但在多php版本下，会失误。
